= Authentication and authorization using Auth0 and Vertx
:hp-tags: OAuth, Auth0, Vertx, Security, REST API

_This is the first - short - post of a serie about Vertx._

Imagine you have a REST API, written using http://vertx.io/[Vertx]. It is working well, but you want to go further: you want to protect it (let authorized users only), or log the users using it, or...

So, as an autonomous developer, you ask Google, and you find tons of examples for tons of libraries and protocols. You will probably be a bit lost, especially if you are not used to authentication / authorization.

The solution I write about is a solution for a given problem, not a silver bullet. The need is: users can use the API given that they are authorized to do so, and they can create an account or use their existing Google or Facebook account. You heard about OAuth2, which fulfills your needs (and is implemented by many major identity providers). The problem is: how do you integrate it to your API?

For sure, you could use the provided APIs from Google, Facebook, ... Their implementation of OAuth2 is quite different, but there are SDK to help. But how can you federate users from differents sources, and assign them authorizations whatever the identity provider? The solution is to use a specialized service, such as https://auth0.com/[Auth0].

*Paragraph about auth0, and JWT*


All right, you just have to add some filter to your application. Vertx provides a way to handle JWT, so it is quite easy to do:

[source,java]
++++
include::https://gist.githubusercontent.com/cdelmas/dcb45c703a25249147fe/raw/78155e103a0dcaa0714ac1d5e6109482489edba5/Main.java
++++

This will parse the Authorization header, extract the token, and pass it to a AuthHandler. You have to provide a AuthHandler, to parse the token and extract authorizations:


[source,java]
++++
include::https://gist.githubusercontent.com/cdelmas/826d38d5eccebdb1ff9e/raw/a36d5f9e42f65bdc50d67d6d56757d8ea9e2e5c9/Auth0TokenVerifier.java
++++

Last, you just write a User class extending AbstractUser to handle the authorities:

[source,java]
++++
include::https://gist.githubusercontent.com/cdelmas/25d0a3d8505dff471844/raw/01db108a429c8c34695000aa594a64d3d06a238d/User.java
++++

Done. You have an API which is totally agnostic of the identity provider, and protected.