= Authentication and authorization using Auth0 and Vertx
:hp-tags: OAuth, Auth0, Vertx, Security, REST API


Imagine you have a resource server, exposing a REST API, written using http://vertx.io/docs/vertx-web/java/[Vertx]. It is working well, but you want to go further: you would like to identify your users, both to let only authorized ones access your app and log activity.

.The big world of authentication and authorization

You don't want to manage your own users database. There is already solutions existing, and it's not fun for you. Moreover, for your users, it would be another account (and password) to create. What about reusing Facebook or Twitter as the identity provider?

So, as an autonomous developer, you ask Google, and you find tons of examples for tons of libraries and protocols. You will probably be a bit lost, especially if you are not used to authentication / authorization.

.The need

The need is quite simple: users can use the API given that they are authorized to do so. They can create an account or use their existing Google+ or Facebook account. You heard about OAuth2, which fulfills your needs (and is implemented by many major identity providers). The problem is: how do you integrate it to your API?

For sure, you could use the provided APIs from Google, Facebook, ... Their implementation of OAuth2 is quite different, but there are SDK to help. But how can you federate users from differents sources, and assign them authorizations whatever the identity provider? The solution is to use a specialized service, such as https://auth0.com/[Auth0].

.Auth0 to the rescue

https://auth0.com/[Auth0] is an Identity Hub as a Service, which support a large number of identity providers and protocols. It has a very interesting free plan, so no excuse to not try it! Among all these protocols (I never imagined that there were so many protocols!), our target: OAuth2. 

We have two main choices for our use case when authenticating on the identity provider (via Auth0): 

* get an access token; this token is given to the API through the Authorization header, and the resource server must call the authorization server (auth0) to validate it and get further details (such as the user profile)
* get an id token using openid connect, this token being a (signed) https://tools.ietf.org/html/rfc7519[Json Web Token]; in this case, the resource server just have to know the secret key to decode the token, and is totally agnostic of the authorization server, because it can contain all the details you need by requiring the matching scopes (e.g. openid, email, name, roles, ...). For more, see https://auth0.com/docs/auth-api[the auth API doc].

For our case, let's use JWT.


.Implementing the solution

All right, you just have to add some kind of filter to your application. Vertx provides a way to handle JWT, so it is quite easy to do:

[source,java]
-------
AuthHandler authHandler = JWTAuthHandler.create(new Auth0TokenVerifier("myapp", applicationId, applicationSecret));
authHandler.addAuthority("create:user");
router.route("/api/*").handler(authHandler);
-------
https://gist.githubusercontent.com/cdelmas/dcb45c703a25249147fe/raw/78155e103a0dcaa0714ac1d5e6109482489edba5/Main.java[source]

This will parse the Authorization header, extract the token, and pass it to a `AuthProvider`. So next, you have to provide that `AuthProvider`, to parse the token and extract authorizations:

[source,java]
-------
public class Auth0TokenVerifier implements AuthProvider {

    private final String audience;
    private final byte[] secret;
    private final String appName;

    // ...

    @Override
    public void authenticate(JsonObject credentials, Handler<AsyncResult<io.vertx.ext.auth.User>> resultHandler) {
        String token = credentials.getString("jwt");
        try {
            Map<String, Object> tokenInfo = verifyToken(token);
            String name = (String) tokenInfo.getOrDefault("name", "unknown"); // TODO fail?
            List<String> permissions = findPermissions(tokenInfo);
            User user = new User(name, permissions);
            resultHandler.handle(Future.succeededFuture(user));
        } catch (Exception e) {
            resultHandler.handle(Future.failedFuture(e));
        }
    }

    private Map<String, Object> verifyToken(String token) throws NoSuchAlgorithmException, InvalidKeyException, IOException, SignatureException, JWTVerifyException {
        JWTVerifier verifier = new JWTVerifier(secret, audience);
        return verifier.verify(token);
    }

    private List<String> findPermissions(Map<String, Object> tokenInfo) {
        List<String> permissions = new ArrayList<>();
        Map<String, Object> appMetadata = (Map<String, Object>) tokenInfo.get("app_metadata");
        if (appMetadata == null) {
            return permissions;
        }
        Map<String, Object> translatorApp = (Map<String, Object>) appMetadata.get(appName);
        if (translatorApp == null) {
            return permissions;
        }
        List<String> appPermissions = (List<String>) translatorApp.get("permissions");
        if (appPermissions == null) {
            return permissions;
        }
        permissions.addAll(appPermissions);
        return permissions;
    }
}
-------
https://gist.githubusercontent.com/cdelmas/826d38d5eccebdb1ff9e/raw/a36d5f9e42f65bdc50d67d6d56757d8ea9e2e5c9/Auth0TokenVerifier.java[source]

Last, you just write a `User` class extending `AbstractUser` to handle the authorities:

[source,java]
-------
public class User extends AbstractUser {

    private final String name;
    private final List<String> permissions;

    public User(String name, List<String> permissions) {
        this.name = name;
        this.permissions = permissions;
    }

    @Override
    protected void doIsPermitted(String permission, Handler<AsyncResult<Boolean>> resultHandler) {
        resultHandler.handle(Future.succeededFuture(permissions.contains(permission)));
    }

    // ...

}
-------
https://gist.githubusercontent.com/cdelmas/25d0a3d8505dff471844/raw/01db108a429c8c34695000aa594a64d3d06a238d/User.java[source]

.The final word

Done. You now have an API which is totally agnostic of the identity provider, and protected. You can now register users using Facebook or Google+ as identity providers (at the time of writing, the free plan limits to 2 the number of identity providers).


