= Authentication and authorization using Auth0 and Vertx
:hp-tags: OAuth, Auth0, Vertx, Security, REST API


Imagine we have a resource server, exposing a REST API, written using http://vertx.io/docs/vertx-web/java/[Vertx]. It is working well, but we want to go further: we would like to identify our users, both to let only authorized ones access our app and log activity.

.The big world of authentication and authorization

We ask Google, and find tons of examples for tons of libraries and protocols: SAML, WS-Federation, OAuth, OpenId. Quite interesting, but very frightening, isn't it?

.The need

Let's focus on our need, which is quite simple: users can use the API provided that they are authorized to do so.

NOTE: The login workflow is out of scope of this post. You can either create a https://auth0.com/docs/quickstart/spa/angularjs/java[login UI] or call directly the Auth0 https://auth0.com/docs/auth-api[authentication API].

We don't want to manage your own users database. It's not fun.footnote:[At least for me.]. Moreover, for our users, it would be another account (and password) to create. What about reusing Facebook or Twitter as the identity provider?

What do social providers have in common? OAuth2.footnote:[Well, they probably have many more in common.]. Good, it seems that it fulfills our needs. Bonus, it is implemented by almost all major identity providers. The problem is: how do we integrate it to your API?

For sure, we could use the APIs from Google, Facebook, directly... Their implementation of OAuth2 is quite different, but there are SDK to help. But we want to federate users from differents sources, and assign them authorizations whatever the identity provider; how can we do that? The solution is to use a specialized service, such as https://auth0.com/[Auth0].

.Auth0 to the rescue

https://auth0.com/[Auth0] is an Identity Hub as a Service, which support a large number of identity providers and protocols.  Among all these protocols (I never imagined that there were so many protocols!), our target: OAuth2. 

We have two main choices for our use case when authenticating on the identity provider (via Auth0): 

* get an access token; this token is given to the API through the Authorization header, and the resource server must call the authorization server (auth0) to validate it and get further details (such as the user profile)
* get an id token using openid connect, this token being a (signed) https://tools.ietf.org/html/rfc7519[Json Web Token]; in this case, the resource server just have to know the secret key to decode the token, and is totally agnostic of the authorization server, because it can contain all the details you need by requiring the matching scopes (e.g. openid, email, name, roles, ...). For more, see https://auth0.com/docs/auth-api[the authentication API doc].

For our case, let's use JWT.


.Implementing the solution

Vertx provides a way to handle JWT, it is as easy as adding a handler:

[source,java]
.https://gist.githubusercontent.com/cdelmas/dcb45c703a25249147fe/raw/78155e103a0dcaa0714ac1d5e6109482489edba5/Main.java[source]
-------
AuthHandler authHandler = JWTAuthHandler.create(new Auth0TokenVerifier("myapp", applicationId, applicationSecret));
authHandler.addAuthority("create:user"); <2>
router.route("/api/*").handler(authHandler); <1>
-------
<1> add the handler
<2> add authority: only users with the permission "create:user" will be able to use the API


The `JWTAuthHandler` will parse the Authorization header, extract the token, and pass it to a `AuthProvider`. So next, you have to provide that `AuthProvider`, to parse the token and extract authorizations:

[source,java]
.https://gist.githubusercontent.com/cdelmas/826d38d5eccebdb1ff9e/raw/a36d5f9e42f65bdc50d67d6d56757d8ea9e2e5c9/Auth0TokenVerifier.java[source]
-------
public class Auth0TokenVerifier implements AuthProvider {

    private final String audience;
    private final byte[] secret;
    private final String appName;

    // ...

    @Override
    public void authenticate(JsonObject credentials, Handler<AsyncResult<io.vertx.ext.auth.User>> resultHandler) {
        String token = credentials.getString("jwt");
        try {
            Map<String, Object> tokenInfo = verifyToken(token);
            String name = (String) tokenInfo.getOrDefault("name", "unknown"); // TODO fail?
            List<String> permissions = findPermissions(tokenInfo);
            User user = new User(name, permissions);
            resultHandler.handle(Future.succeededFuture(user));
        } catch (Exception e) {
            resultHandler.handle(Future.failedFuture(e));
        }
    }

    private Map<String, Object> verifyToken(String token) throws NoSuchAlgorithmException, InvalidKeyException, IOException, SignatureException, JWTVerifyException {
        JWTVerifier verifier = new JWTVerifier(secret, audience); <1>
        return verifier.verify(token);
    }

    private List<String> findPermissions(Map<String, Object> tokenInfo) {<2>
        List<String> permissions = new ArrayList<>();
        Map<String, Object> appMetadata = (Map<String, Object>) tokenInfo.get("app_metadata");
        if (appMetadata == null) {
            return permissions;
        }
        Map<String, Object> translatorApp = (Map<String, Object>) appMetadata.get(appName);
        if (translatorApp == null) {
            return permissions;
        }
        List<String> appPermissions = (List<String>) translatorApp.get("permissions");
        if (appPermissions == null) {
            return permissions;
        }
        permissions.addAll(appPermissions);
        return permissions;
    }
}
-------
<1> Token verification: the token is decoded and the signature is verified. You can debug a JWT http://jwt.io[here].
<2> Permissions are extracted from the token. Auth0 provides a app_metadata object to store arbitrary data such as roles.

Last, you just write a `User` class extending `AbstractUser` to handle the authorities:

[source,java]
-------
public class User extends AbstractUser {

    private final String name;
    private final List<String> permissions;

    public User(String name, List<String> permissions) {
        this.name = name;
        this.permissions = permissions;
    }

    @Override
    protected void doIsPermitted(String permission, Handler<AsyncResult<Boolean>> resultHandler) {
        resultHandler.handle(Future.succeededFuture(permissions.contains(permission)));
    }

    // ...

}
-------
https://gist.githubusercontent.com/cdelmas/25d0a3d8505dff471844/raw/01db108a429c8c34695000aa594a64d3d06a238d/User.java[source]

.The final word

We're done. Now, we have an API which is totally agnostic of the identity provider, and protected.

At the time of writing, Auth0 has a free plan allowing up to 7000 users and 2 social identity providers.




